Repository mercari/spanner-autoscaler, pull requests merged in 2020-08, with the labels that each got.

#19 Add EventRecorder to syncer
  pkg/controllers/spannerautoscaler_controller.go
  pkg/syncer/syncer.go
Labels: release/patch, size/S

#20 create release with patch in addition to major and minor
  .github/workflows/release.yml
Labels: size/XS

#21 Fix typo from recoder to recorder
  pkg/controllers/spannerautoscaler_controller.go
Labels: size/S

#22 Add project id and instance id to kubernetes event
  pkg/controllers/spannerautoscaler_controller.go
Labels: size/XS
