Repository mercari/spanner-autoscaler, pull requests merged in 2022-02, with the labels that each got.

#65 Add `validation` and `defaulting` webhooks
  Makefile
  api/v1beta1/spannerautoscaler_types.go
  api/v1beta1/spannerautoscaler_webhook.go
  api/v1beta1/spannerautoscaler_webhook_test.go
  api/v1beta1/webhook_suite_test.go
  config/crd/bases/spanner.mercari.com_spannerautoscalers.yaml
  config/deploy-dev/kustomization.yaml
  config/samples/spanner_v1beta1_spannerautoscaler.yaml
  docs/webhook_development.md
Labels: enhancement, size/L

#66 Switch all internal compute capacity to processing units only
  api/v1alpha1/spannerautoscaler_conversion.go
  api/v1beta1/spannerautoscaler_types.go
  api/v1beta1/spannerautoscaler_webhook.go
  api/v1beta1/spannerautoscaler_webhook_test.go
  config/crd/bases/spanner.mercari.com_spannerautoscalers.yaml
  controllers/spannerautoscaler_controller.go
  controllers/spannerautoscaler_controller_test.go
  pkg/syncer/syncer_test.go
Labels: size/L

#68 Remove custom `logging` package
  config/manager/kustomization.yaml
  controllers/spannerautoscaler_controller.go
  pkg/logging/context.go
  pkg/metrics/fake.go
  pkg/metrics/metrics.go
  pkg/spanner/fake.go
  pkg/spanner/spanner.go
  pkg/syncer/fake/fake.go
  pkg/syncer/syncer.go
  pkg/syncer/syncer_test.go
Labels: enhancement, size/L

#69 Change `pkg` to `internal` and improve logging
  .dockerignore
  Dockerfile
  config/manager/kustomization.yaml
  controllers/spannerautoscaler_controller.go
  controllers/spannerautoscaler_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  internal/metrics/fake.go
  internal/metrics/metrics.go
  internal/spanner/fake.go
  internal/spanner/spanner.go
  internal/syncer/fake/fake.go
  internal/syncer/syncer.go
  internal/syncer/syncer_test.go
  main.go
Labels: enhancement, size/L, release/minor

#70 Fix CI: goreleaser
  .github/workflows/release.yml
  .goreleaser.yml
  go.mod
Labels: size/S, release/minor, ignore-for-release-notes

#72 Correct GitHub Actions go mod cache prefix
  .github/workflows/test.yml
Labels: size/XS

#67 Add unit tests for v1alpha1 ConvertTo
  api/v1alpha1/spannerautoscaler_conversion.go
  api/v1alpha1/spannerautoscaler_conversion_test.go
  api/v1alpha1/suite_test.go
Labels: size/L

#73 Add more tests for webhook defaults
  api/v1beta1/spannerautoscaler_webhook_test.go
Labels: size/L

#74 Add unit tests for v1alpha1 ConvertFrom
  api/v1alpha1/spannerautoscaler_conversion_test.go
Labels: size/L

#76 Add `delete` functionality for schedule resources
  config/crd/bases/spanner.mercari.com_spannerautoscaleschedules.yaml
  controllers/spannerautoscaler_controller.go
  controllers/spannerautoscaleschedule_controller.go
  main.go
Labels: size/L
