Repository mercari/spanner-autoscaler, pull requests merged in 2022-03, with the labels that each got.

#77 Switch from command line flags to config file based options
  Makefile
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  main.go
Labels: size/S

#80 Fix `RoleBinding` and `namespace` in samples
  Makefile
  config/samples/rbac/role.yaml
  config/samples/spanner_v1beta1_spannerautoscaler.yaml
  config/samples/spanner_v1beta1_spannerautoscaleschedule.yaml
Labels: size/XS

#82 Create CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: size/M
