Repository mercari/spanner-autoscaler, pull requests merged in 2022-10, with the labels that each got.

#87 Add additional information for `scaledownStepSize`
  docs/crd-reference.md
Labels: size/XS

#88 Update documentation for `scaledownStepSize` value constraint
  api/v1beta1/spannerautoscaler_types.go
Labels: size/XS

#89 Allow `--scale-down-interval` to be overwritten by SpannerAutoscaler resource
  api/v1beta1/spannerautoscaler_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/spanner.mercari.com_spannerautoscalers.yaml
  controllers/spannerautoscaler_controller.go
  controllers/spannerautoscaler_controller_test.go
  docs/crd-reference.md
Labels: size/M

#90 Migrate from `go get` to `go install`
  Makefile
Labels: size/S
