Repository mercari/spanner-autoscaler, pull requests merged in 2022-01, with the labels that each got.

#55 Fix directory structure and migrate tests to Ginkgo
  .dockerignore
  .github/workflows/test.yml
  Dockerfile
  Makefile
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/spannerautoscaler_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/spannerautoscaler_controller.go
  controllers/spannerautoscaler_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  pkg/controllers/spannerautoscaler_controller_test.go
  pkg/spanner/spanner.go
  pkg/syncer/syncer.go
  pkg/syncer/syncer_test.go
Labels: size/XXL

#56 Remove custom pkg `pointer`
  controllers/spannerautoscaler_controller.go
  controllers/spannerautoscaler_controller_test.go
  go.mod
  go.sum
  pkg/metrics/metrics.go
  pkg/pointer/pointer.go
  pkg/pointer/pointer_test.go
  pkg/spanner/spanner.go
  pkg/syncer/syncer.go
  pkg/syncer/syncer_test.go
Labels: release/patch, size/M

#57 Fix `main.go` path in `.goreleaser.yml`
  .goreleaser.yml
Labels: size/XS, release/patch, ignore-for-release-notes

#59 Add column about current status, when execute `kubectl get spannerautoscaler`
  api/v1alpha1/spannerautoscaler_types.go
  config/crd/bases/spanner.mercari.com_spannerautoscalers.yaml
Labels: size/S, release/patch

#60 Fix the CI workflows to pass secrets
  .github/workflows/release.yml
  .github/workflows/tag.yml
Labels: size/XS, release/patch, ignore-for-release-notes

#62 Set a Spanner client log
  pkg/metrics/metrics.go
  pkg/syncer/syncer.go
Labels: size/XS

#63 Use the same golangci-lint version in the Dev and the CI env
  .github/workflows/golangci-lint.yml
  Makefile
Labels: size/XS, ignore-for-release-notes

#64 Migrate `SpannerAutoscaler` controller and packages to use `v1beta1`
  Makefile
  api/v1alpha1/spannerautoscaler_conversion.go
  api/v1alpha1/spannerautoscaler_types.go
  api/v1beta1/spannerautoscaler_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bin/.gitkeep
  config/crd/bases/spanner.mercari.com_spannerautoscalers.yaml
  controllers/spannerautoscaler_controller.go
  controllers/spannerautoscaler_controller_test.go
  go.mod
  go.sum
  pkg/metrics/metrics.go
  pkg/spanner/spanner.go
  pkg/syncer/fake/fake.go
  pkg/syncer/syncer.go
  pkg/syncer/syncer_test.go
Labels: enhancement, size/XL
